spring.application.name=Wishlist_java

# Spring DataSource (MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/shopping_wishlist?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=qhdks100%

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.com.wishlist.model.dao=TRACE
logging.level.org.mybatis=DEBUG

# MyBatis
#mybatis.config-location= classpath:mybatis-config.xml
#mybatis.mapper-locations= classpath:mapper/*.xml
